export type RootStackParamList = {
  Welcome: undefined;
  Quiz: undefined;
  Reveal: undefined;
  MoodPick: undefined;
  EstadosInteres: undefined;
  Home: undefined;
  Profile: undefined;
  Squads: undefined;
  SquadDetail: { squadId: string };
  Festivals: { highlightFestivalId?: string } | undefined;
  ArtistDetail: { artistId: string; artistName: string };
  VenueDetail: { venueId: string; venueName: string };
  Torneo: undefined;
  SquadTorneo: { squadId: string };
  CommunityTrends: undefined;
  ConcertAlbum: undefined;
  Recap: undefined;
  Contacts: undefined;
  Settings: undefined;
};
